"""
DIGM 131 - Week 8 Demo: File I/O and JSON
==========================================
Learn to read/write files, use context managers, and serialize
Maya scene data to JSON so it can be saved and reconstructed.
"""

import os
import json
import maya.cmds as cmds

# ============================================================
# PART 1: Basic File Writing and Reading
# ============================================================

# os.path.join builds paths that work on any OS.
# We'll write to the user's home directory for simplicity.
home = os.path.expanduser("~")
output_dir = os.path.join(home, "maya_exports")

# Create the directory if it doesn't exist yet
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Created directory: {output_dir}")

# --- Writing a file ---
# 'with' is a CONTEXT MANAGER -- it automatically closes the file
# when the block ends, even if an error occurs.  Always use 'with'.
file_path = os.path.join(output_dir, "hello.txt")

with open(file_path, "w", encoding="utf-8") as f:  # "w" = write mode (overwrites)
    f.write("Hello from Maya!\n")
    f.write("This file was generated by a script.\n")

print(f"Wrote: {file_path}")

# --- Reading a file ---
with open(file_path, "r", encoding="utf-8") as f:  # "r" = read mode
    contents = f.read()
print("File contents:")
print(contents)

# --- Reading line by line ---
with open(file_path, "r", encoding="utf-8") as f:
    for line_number, line in enumerate(f, start=1):
        print(f"  Line {line_number}: {line.strip()}")


# ============================================================
# PART 2: os and pathlib Basics
# ============================================================
# Common os.path operations you'll use often:
print("\n--- Path Utilities ---")
print("Home dir:      ", home)
print("Join example:  ", os.path.join(home, "Documents", "test.txt"))
print("File exists?   ", os.path.exists(file_path))
print("Is a file?     ", os.path.isfile(file_path))
print("Is a dir?      ", os.path.isdir(output_dir))
print("Directory of:  ", os.path.dirname(file_path))
print("Filename only: ", os.path.basename(file_path))

# pathlib is a more modern alternative (Python 3.4+):
from pathlib import Path

p = Path(home) / "maya_exports" / "hello.txt"   # / operator joins paths
print("pathlib path:  ", p)
print("Stem (no ext): ", p.stem)       # "hello"
print("Suffix:        ", p.suffix)     # ".txt"


# ============================================================
# PART 3: JSON -- Saving Structured Data
# ============================================================
# JSON is a lightweight text format perfect for saving settings,
# scene layouts, tool configurations, etc.

# Let's create some objects in Maya and export their data.
cmds.polyCube(name="export_cube")
cmds.move(3, 1, -2, "export_cube")
cmds.polySphere(name="export_sphere")
cmds.move(-4, 0.5, 1, "export_sphere")

def gather_scene_data(object_names):
    """Collect transform data for a list of Maya objects."""
    scene_data = []
    for obj in object_names:
        if not cmds.objExists(obj):
            print(f"Warning: {obj} not found, skipping.")
            continue
        pos = cmds.xform(obj, q=True, worldSpace=True, translation=True)
        rot = cmds.xform(obj, q=True, worldSpace=True, rotation=True)
        scl = cmds.xform(obj, q=True, worldSpace=True, scale=True)
        obj_type = cmds.objectType(cmds.listRelatives(obj, shapes=True)[0])
        scene_data.append({
            "name": obj,
            "type": obj_type,
            "position": pos,
            "rotation": rot,
            "scale": scl,
        })
    return scene_data

objects_to_export = ["export_cube", "export_sphere"]
data = gather_scene_data(objects_to_export)

# --- Write JSON ---
json_path = os.path.join(output_dir, "scene_layout.json")

with open(json_path, "w", encoding="utf-8") as f:
    # indent=2 makes the file human-readable (pretty-printed)
    json.dump(data, f, indent=2)

print(f"\nExported scene data to: {json_path}")

# --- Read JSON back ---
with open(json_path, "r", encoding="utf-8") as f:
    loaded_data = json.load(f)

print("Loaded data:")
for item in loaded_data:
    print(f"  {item['name']}  type={item['type']}  pos={item['position']}")


# ============================================================
# PART 4: Reconstruct Scene from JSON
# ============================================================

def rebuild_from_json(json_file):
    """Delete existing objects and recreate them from saved JSON."""
    with open(json_file, "r", encoding="utf-8") as f:
        items = json.load(f)

    for item in items:
        # Remove old object if it exists
        if cmds.objExists(item["name"]):
            cmds.delete(item["name"])

        # Create the right primitive based on saved type
        if item["type"] == "mesh":
            # We stored the shape type; for a simple demo we check the name
            if "sphere" in item["name"].lower():
                cmds.polySphere(name=item["name"])
            else:
                cmds.polyCube(name=item["name"])

        # Apply saved transforms
        cmds.xform(item["name"], worldSpace=True, translation=item["position"])
        cmds.xform(item["name"], worldSpace=True, rotation=item["rotation"])
        cmds.xform(item["name"], worldSpace=True, scale=item["scale"])

    print(f"Rebuilt {len(items)} objects from {json_file}")

# Uncomment to test:
# rebuild_from_json(json_path)
